rustic-rs/rustic

- src/commands/backup.rs
#9 had the unwanted side effect that the progress bar already started running during the collection of backup size. This is now fixed
> backup: fix progress bar

- Cargo.lock
- Cargo.toml
- README.md
- src/backend/cache.rs
- src/backend/choose.rs
- src/backend/decrypt.rs
- src/backend/dry_run.rs
- src/backend/local.rs
- src/backend/mod.rs
- src/backend/rest.rs
- src/blob/packer.rs
- src/commands/backup.rs
- src/commands/check.rs
- src/commands/forget.rs
- src/commands/mod.rs
- src/commands/prune.rs
- src/commands/restore.rs
- src/index/binarysorted.rs
- src/index/mod.rs
Open points are:
If a cache base dir is not explicitely given, rustic first tries to find a restic cache dir for the given repo and uses this one exists. If not, it searches for a rustic cache dir.
> Add possibilty to use a cache

- src/backend/cache.rs
- src/commands/mod.rs
Now the logic is:
- `--no-cache` implies no cache is used
- else: use cache, if possible. If there is any error in creating a cache dir, use no cache.
closes #49
> cache: Make options more obvious to work with

- src/commands/mod.rs
Add the `global = true` option for all global clap arguments (except `--repository` which is a needed one)
closes #50
> Make (most) CLI options global

- src/backend/decrypt.rs
- src/commands/check.rs
- src/commands/restore.rs
Limit the number of concurrent reads/writes.
This is needed for some remote backends which refuse too many connections.
Also reduces memory requirements.
> Limit concurrent operations

- Cargo.lock
- Cargo.toml
- src/backend/choose.rs
- src/backend/mod.rs
- src/backend/rclone.rs
- src/commands/mod.rs
Adds the rclone backend. 
Note that different to the restic rclone backend implementation, this starts an `rclone` to listen on http://localhost and connects via TCP.
closes #68 
Checklist:
> Add rclone Backend

- src/backend/local.rs
- src/commands/backup.rs
- src/commands/cat.rs
- src/commands/config.rs
- src/commands/init.rs
- src/commands/mod.rs
- src/commands/prune.rs
- src/repo/configfile.rs
Adds the `config` command which allows to set repository options which are saved in the config file.
Currently the following options are available:
- `--set-version`
- `--set-compression`
Also adds these options to `init` to set these parameters when initializing a repo.
This feature will be later also used for #52 
This PR also changes the `cat config` command: Here is no longer an ID needed.
> Add config command

- Cargo.lock
- Cargo.toml
- src/archiver/archiver_impl.rs
- src/blob/mod.rs
- src/blob/packer.rs
- src/commands/backup.rs
- src/commands/config.rs
- src/commands/prune.rs
- src/commands/repoinfo.rs
- src/index/binarysorted.rs
- src/index/mod.rs
- src/repo/configfile.rs
- src/repo/indexfile.rs
> Allow to customize pack size

- src/commands/prune.rs
`--repack-cacheable-only` did not work when specified together with `--repack-uncompressed`.
This is fixed by this PR
> prune: fix --repack-cacheable-only in combination with --repack-uncompressed

- src/backend/decrypt.rs
- src/backend/dry_run.rs
- src/blob/packer.rs
- src/commands/restore.rs
- src/index/mod.rs
Only happens when compressed blobs are repacked and if --repack-fast is
not given.
The cause for the bug was, that compressed blobs were not decompressed before re-compressing and storing them again. This PR adds the decompression at the point of decrypting the data, such that it can't be forgotten if it is again used in other parts.
closes #88
> prune: fix repo corruption with compressed blobs

- src/backend/choose.rs
- src/blob/tree.rs
- src/commands/cat.rs
- src/commands/diff.rs
- src/commands/ls.rs
- src/commands/restore.rs
Allows additionally using `SNAP:PATH`for some commands which so far needed `SNAP`.
For instance you can now use `rustic-rs ls latest:/home`.
This is added for `ls`, `cat`, `diff` and `restore`.
For `restore` this is especially useful as it allows to in-place restore subpaths, e.g.
`rustic-rs restore snap:/home /home`
This PR is also a requirement for #92
> Allow specifying snapshot with path for some commands

- src/backend/local.rs
- src/commands/restore.rs
This PR adds the `restore --delete` option which removes existing contents in the destination which are not present in the snapshot/dir to restore.
see #92 
Note: this PR does NOT change the behavior/bug described in #105
> restore: add --delete option

- src/backend/local.rs
> local backend: truncate file to correct length (if it exists)

- Cargo.lock
- Cargo.toml
- src/archiver/archiver_impl.rs
- src/backend/ignore.rs
- src/backend/node.rs
This PR does escape all filenames, as this is also done so in restic, see #34 .
It however does not produce the identical escapes as done in restic, but simply escapes all non-ASCII letters and the control ASCII letters.
The format seems to be readable by restic; therefore with this PR the repo format generated by rustic can be completely processed by restic with identical results.
Moreover, when reading escaped filenames, not only the escapes produced by rustic are processed, but also all escapes produced by restic; therefore with this PR the repo format generated by restic can be completely processed by rustic with identical results.
Note that, however, for non-ASCII file names, the names saved in the trees may differ for restic and rustic. This implies that doing follow-up-backups with …
> Add escaping of filenames (+support non-unicode filenames)

- .github/workflows/tests.yaml
fixes a typo in the MacOs tests which resulted in a warning
> CI: fix typo

- Cargo.lock
- Cargo.toml
- src/backend/cache.rs
- src/backend/choose.rs
- src/backend/decrypt.rs
- src/backend/dry_run.rs
- src/backend/hotcold.rs
- src/backend/local.rs
- src/backend/mod.rs
- src/backend/rclone.rs
- src/backend/rest.rs
- src/blob/packer.rs
- src/commands/cat.rs
- src/commands/init.rs
- src/commands/key.rs
- src/commands/restore.rs
- src/index/mod.rs
This PR does a bit of refactoring in the backend:
- uses `Bytes` instead of `Vec<u8>` (this allows to cheaply `clone()` data and saves memory)
- Save unfinished pack files in-memory (in the Bytes struct) instead of using a temporary file. This should make the packing even faster. However, it will increase the memory usage by the size of the pack file. As most modern distributions already use a tmpfs for `/tmp`, the overall memory consumption is however not changed in that case.
- Allows to set options for backends.
- Add retries for remote backends (actually the two upper changes are prerequisites for this change)
TODOs:
closes #86
> Don't use temporary files; add retries to rest/rclone backend

- src/blob/packer.rs
- src/commands/config.rs
- src/repo/configfile.rs
Also fixes a typo which did automatically set the grow factor for data packs as the one for tree packs.
> Allow to specify upper limits for packfile sizes

- .github/workflows/release.yaml
- Cargo.lock
- Cargo.toml
- src/commands/mod.rs
- src/commands/self_update.rs
closes #119 
Note that this PR includes a change in the CI as it selects the first matching file independent of the file suffix; therefore the `.sha256` files need to be removed.
> add command self-update

- src/blob/packer.rs
- src/commands/config.rs
- src/commands/prune.rs
- src/repo/configfile.rs
This PR repacks packs which are too small or too large.
By default a tolerated pack size is 30%..unlmited of the targeted pack size.
Note that during backup or repacks larger or smaller pack files than the targeted pack size are regularly generated:
- larger pack sizes as blobs are added as long as the pack size is smaller than the targeted pack size. This means that packs can be up to 1 blob larger than the targeted pack size
- smaller pack sizes if generation of pack files ends but the targeted pack size is not yet reached. This means that packs can contain only 1 blob (which could contain only 1 byte data) + encryption + header.
The lower and upper toleration limits can be configured using the `config` command.
To deactive this feature, use
```
rustic-rs config …
```
> prune: repack packs which are too small or too large

- src/archiver/parent.rs
- src/commands/backup.rs
Adds the options `--ignore-ctime` and `--ignore-indode` to be compatible with restic
> backup/parent: Use ctime and mtime; add --ignore options

- src/commands/snapshots.rs
- src/repo/snapshotfile.rs
This PR also adds the option `--all` which gives the previous behavior.
> snapshots: summarize snapshots with identical trees

- src/commands/snapshots.rs
After #170 it is much more convenient to group snapshots by default.
> snapshots: group by hosts and paths as default

- src/backend/ignore.rs
- src/commands/backup.rs
This tackles the first issue in #43.
With this PR, multiple backup sources are allowed. However, if multiple source are given, rustic creates multiple snapshots - one per given source.
> backup: Allow multiple sources

- Cargo.lock
- Cargo.toml
- README.md
- examples/local.toml
- examples/ovh-hot-cold.toml
- examples/rustic.toml
- src/backend/ignore.rs
- src/commands/backup.rs
- src/commands/forget.rs
- src/commands/mod.rs
- src/commands/rustic_config.rs
- src/commands/snapshots.rs
- src/commands/tag.rs
- src/repo/snapshotfile.rs
TODOs:
Will stay open for follow-up PRs
> Add config file support

- .github/workflows/release.yaml
- Cargo.toml
- examples/local.toml
- examples/ovh-hot-cold.toml
- examples/rustic.toml
- src/commands/self_update.rs
Note that this change break the self-update functionality when starting from previous versions.
However, self-update so far is only contained in release 0.3.0.
I think it's reasonable to have a working self-update starting from the upcoming 0.3.1.
> change binary name to rustic

- .github/workflows/audit.yml
- Cargo.lock
- Cargo.toml
currently failing due to security issue in chrono (fixed in unreleased version 0.4.20), see https://github.com/chronotope/chrono/issues/602
> add rust audit

- Cargo.lock
- Cargo.toml
- src/backend/rclone.rs
Currently, rustic saves a `.htpasswd` at `/tmp` to use as rclone authentication.
This PR uses the environmental variables introduced in rclone 1.52.2. This simplifies the code and removes build dependencies.
This change also makes rustic independent from a `/tmp` directory.
> Simplify rclone backend (using rclone > 1.52.2)

- src/blob/packer.rs
- src/commands/check.rs
- src/commands/prune.rs
- src/id.rs
- src/index/binarysorted.rs
- src/index/mod.rs
- src/repo/indexfile.rs
- src/repo/mod.rs
- src/repo/packfile.rs
- test-bats/simple.bats
closes #210 
So far missing is the warm-up possibility for the data packs that are checked.
So far, there is only the option to read all data packs, so I'll leave the warm-up to future PRs which then might also add more posibilites to only read some pack files, e.g.
- only tree pack files (these could be actually always be read)
- only a fixed subset of the packfiles (e.g. starting with given prefixes)
- a random subset of the packfiles
- only the packfiles which are referenced by one or a set of snapshots
> check: Add --read-data

- src/commands/repair.rs
`repair index` saved the modified index only if both packs and packs-to-delete in this index remain. It was due to an logic error.
This is fixed by this PR.
> fix repair index

- src/archiver/archiver_impl.rs
- src/backend/ignore.rs
- src/commands/backup.rs
The option `--as-path` lets rustic set an other path instead of the path specified by SOURCE. It also generates the tree structure according to this given path.
Example:
If you have the files `/dir/a` and `/dir/subdir/b` and call `rustic backup /dir`, the snapshot will contain
```
/dir
/dir/a
/dir/subdir
/dir/subdir/b
```
If you call `rustic backup /dir --as-path /my/directory`, it will generate
```
/my
/my/directory
/my/directory/a
/my/directory/subdir
/my/directory/subdir/b
```
> backup: Add --as-path option

- Cargo.lock
- Cargo.toml
- src/archiver/archiver_impl.rs
- src/commands/backup.rs
closes #294 
This doesn't change anything in the `restore` command, but the restore command already only works with the trees within the snapshot. So absolute/relative paths work there. The only left-open point is to maybe use the absolute path as restore target if no target is given.
> backup: Allow relative paths

- Cargo.lock
- Cargo.toml
- src/archiver/archiver_impl.rs
- src/chunker.rs
This makes use of rayon's threadpool and therefore improves performance especially for lots of files.
Tests show also a better parallelization for a single large file.
Also simplifies dependencies.
> backup: Use rayon to parallelize hashing

- src/backend/local.rs
- src/backend/node.rs
- src/commands/restore.rs
A rework of the treatment of existing files. 
The default is now to not read files with matching size and length (closes #326), but the new option `--ignore-mtime` is available to skip this check.
closes #332 
closes #105
> restore: Overwork treatment of existing files

- examples/ovh-hot-cold.toml
- src/commands/helpers.rs
- src/commands/prune.rs
- src/commands/repair.rs
- src/commands/restore.rs
- src/repository/mod.rs
This PR moves the warm-up options from the commands `restore`, `repair`, `prune` (these are the three commands where it is currently used) to to repository options. This consolidates some code.
Another benefit is that this makes it possible to define warm-up in the config file.
> repository: integrate warm-up options

- Cargo.lock
- Cargo.toml
- src/cdc/LICENSE.txt
- src/cdc/README.md
- src/cdc/mod.rs
- src/cdc/polynom.rs
- src/cdc/rolling_hash.rs
- src/chunker.rs
- src/main.rs
> fix cdc compile errors by integrating cdc

- .github/workflows/release.yaml
- src/backend/local.rs
This is needed to get rustic to build on OpenBSD. Lightly run tested the build against a local restic repo.
> Enable building on OpenBSD

- .github/workflows/release.yaml
- src/backend/local.rs
openbsd seems to lack toolchain support, see e.g. https://github.com/rust-lang/rustup/issues/2168
freebsd got an linking error
So, only netbsd is added to the CI here...
> fix CI for *bsd

- Cargo.lock
- Cargo.toml
- examples/par2.toml
- src/backend/local.rs
- src/commands/helpers.rs
- src/id.rs
- src/repository/mod.rs
This PR adds the possibility to configure hooks (after creating files and after removing files) for the local backend.
This is currently only possible in the config file.
An example config to use the hook to create par2 error correction information is also added.
closes #445
> Local backend hooks

- changelog/new.txt
- src/backend/ignore.rs
- src/commands/backup.rs
- src/commands/forget.rs
- src/commands/mod.rs
- src/commands/rustic_config.rs
- src/repofile/snapshotfile.rs
- src/repository/mod.rs
closes #459 
This PR also removes the possibility to specify repository options under the `[global]` section. If you encounter errors, please move these options under `[repository]`.
> TOML config: Abort with error on unknown fields

- changelog/new.txt
- src/backend/ignore.rs
- src/commands/backup.rs
- src/commands/diff.rs
- src/repofile/snapshotfile.rs
Note: This PR breaks the default behavior when multiple sources are given in the command line.
The old behavior was to generate one snapshot per source, now one snapshot is generated which contains all sources.
The behavior when no source is given is unchanged, i.e. here still all sources are read from the config file.
However, the config file now also accepts multiple path within one source, i.e. `source = "path1 path2"` is possible.
Moreover, with this PR paths given by command line or config file are always first sanitized before being used.
This is necessary to avoid confusion when users use paths in different order or overlapping paths in one place.
As side effect is that paths that cannot be sanitized (e.g. absolute paths not present in the system) will give an error.
Errors in the …
> Allow multiple sources within one snapshot

- README.md
- changelog/new.txt
- src/archiver/archiver_impl.rs
- src/blob/packer.rs
- src/blob/tree.rs
- src/commands/backup.rs
- src/commands/merge_cmd.rs
- src/commands/mod.rs
- src/repofile/snapshotfile.rs
This PR adds the `merge` command which allows to merge multiple snapshots.
It also fixes a minor bug how multiple paths were saved using #458.
The merging strategy is as follows:
- If files only exist in one of the snapshots, add this file to the newly created one
- If files with identical names but different content exist, take the file with newest mtime.
closes #43 
TODO:
> New command merge

- Cargo.lock
- Cargo.toml
- changelog/new.txt
- src/backend/rclone.rs
- src/repofile/snapshotfile.rs
This PR adds the option to filter snapshots by a given script in the [rhai](https://rhai.rs/book/index.html) scripting language.
You can use something like
```
rustic snapshots --filter '|sn| sn.time < "2023-03-08" && ("my_tag" in sn.tags ||  sn.host != "xx_host")'
```
Note that the filter options are available in many commend, e.g. `tag`, `forget`, `copy`, `merge` and all commands which allow to use `latest` as snapshot
All fields are available and are represented in Rhai as Object Map (i.e. like JSON).
Note that when comparing times, this is actually a string-compare!
TODO:
> Add scriptable snapshot filter option

- changelog/new.txt
- src/commands/helpers.rs
- src/commands/mod.rs
Also adds the option `--progress-interval` as command argument and in config file (before only available using the env variable)
closes #515
> Add --no-progress option

- Cargo.toml
- changelog/new.txt
- src/backend/ignore.rs
- src/backend/local.rs
#522 breaks building on OpenBSD because there is no xattr support.
> OpenBSD does not support extended file attributes

- src/repofile/snapshotfile.rs
This PR allows to specify whitespaces in paths in the config file by surrounding them by `"` or `'`
closes #558
> backup: Allow to treat whitespaces in paths in config file

- src/backend/node.rs
- src/commands/restore.rs
closes #561 (when used with `--delete`) 
Note that rustic never deletes existing files unless the `--delete` option is given. On the other side, it can only treat some situations like existing symlinks correctly by deleting and re-creating them. This means, this PR corrects the behavior for existing content when using `--delete` but doesn't fully help without `--delete`.
> restore: Treat all existing contents correctly

- src/archiver/file_archiver.rs
- src/cdc/rolling_hash.rs
- src/chunker.rs
This initializes the chunker once instead of once-per-file and therefore speeds up the backup of many files a lot.
> Optimize chunker

- changelog/new.txt
- src/commands/prune.rs
This PR adds the `--repack-all` option to `prune` which simply repacks all packs.
This is handy if you want to change the compression (level) and ensure that each blob is re-compressed again.
Also nice to test repacking without the need to create repack reasons.
> prune: Add option --repack-all

- changelog/new.txt
- src/archiver/tree_archiver.rs
related to #541 - the case having no parent wasn't implemented properly.
> backup: fix dir stats

- changelog/new.txt
- src/commands/forget.rs
This PR interprets the use of value `-1` (negative 1) for `--keep-*` options to mean "keep all".
So `--keep-hourly -1` would mean "keep all hourly snapshots" etc:
```shell
$ ./target/release/rustic -r ~/rstc1/ forget --prune -n --keep-hourly -1
using no config file (./rustic.toml doesn't exist)
enter repository password: 
[INFO] repository local:/Users/thndrbrrr/rstc1/: password is correct.
[INFO] using cache at /Users/thndrbrrr/Library/Caches/rustic/a35ef0a3a66303a26a652040f5eb53d471fac3cf33779126b960c33184b59621
snapshots for (host [EP-ML-10471], label [], paths [/Users/thndrbrrr/devel/misc/thndrbrrr/rustic/test-bats])
| ID       | Time                | Host        | Label | Tags | Paths                                                              | Action | Reason | …
```
> forget: Interpret '--keep-X -1' as 'keep all X'

- src/backend/local.rs
While building rustic-0.5.2 on OpenBSD current:
```
warning: unused import: `anyhow::Context`
--> src/backend/local.rs:10:5
|
10 | use anyhow::Context;
|     ^^^^^^^^^^^^^^^
|
note: the lint level is defined here
--> src/main.rs:23:5
|
23 |     unused,
|     ^^^^^^
= note: `#[warn(unused_imports)]` implied by `#[warn(unused)]`
```
Proposed diff should actually be part of 3d72aee.
> Silence build warning on OpenBSD

- changelog/new.txt
- examples/full.toml
- src/backend/ignore.rs
- src/commands/backup.rs
- src/commands/configfile.rs
- src/commands/copy.rs
- src/commands/forget.rs
- src/commands/mod.rs
- src/repofile/snapshotfile.rs
- src/repository/mod.rs
This PR optimizes the configuration of rustic:
- filter options can now be given at any place in the CLI
- rustic now allows multiple config files
- the command `show-config` has been added to display the configuration from config files
> Config updates

- changelog/new.txt
- src/backend/ignore.rs
closes #650 
Note: This doesn't close #117, it only makes rustic not crash and ignore these links in the backup.
> backup: Don't crash on non-unicode link targets

- changelog/new.txt
- src/backend/node.rs
With this PR rustic doesn't fail when xattrs have a JSON `null` value.
Maybe closes #638
> xattrs: Allow null value in JSON

- changelog/new.txt
- src/config.rs
Fixes #652 
For all profile names, it will look for configuration files in the following paths and in the following order:
- User-specific config path (same as it always was), e.g. `~/.config/rustic/{profile_name}.toml` on linux
- Global config path: `/etc/rustic/{profile_name}.toml` on Linux and MacOS, `%PROGRAMDATA%\config\rustic\{profile_name}.toml` on Windows
- Current directory: `./{profile_name}.toml`
It will just use the first found file, meaning that if you have a config in the user-specific config path, it will override the config with the same name in the global config path, ignoring everything on it. 
`use-profile` works normally, meaning you can have a user-specific config "inheriting" from the global config.
On smaller behavior changes, I removed the check if the directory …
> Use global config files when user-specific file doesn't exist

- changelog/new.txt
- crates/rustic_core/src/backend/decrypt.rs
- src/commands/restore.rs
The restore command used to download each needed blob by its own.
This PR checks if there are many needed blobs which form a contiguous piece of data within a pack file and downloads them together.
This should reduce repository operations and speed-up the restore especially for remote/high latency backends.
Also the restore path is no longer saved once per blob in the file, but only once per file. So this PR should reduce memory for large files-to-restore.
> restore: Download multiple contiguous blobs in one request

- changelog/new.txt
- crates/rustic_core/src/repository.rs
Useful for commands that requires interactive input
tested on Linux
> feat: wait for password-command to exit

- changelog/new.txt
- crates/rustic_core/src/backend.rs
- crates/rustic_core/src/commands.rs
- crates/rustic_core/src/commands/repoinfo.rs
- crates/rustic_core/src/lib.rs
- crates/rustic_core/src/repository.rs
- src/commands/repoinfo.rs
- src/helpers.rs
Also adds new options `--json`, `--only-files`, `--only-index` to the `repoinfo` command.
Closes #627
> Refactor repoinfo

- Cargo.lock
- Cargo.toml
- changelog/new.txt
- crates/rustic_core/Cargo.lock
- crates/rustic_core/Cargo.toml
- crates/rustic_core/src/lib.rs
- crates/rustic_core/src/repository.rs
- src/commands/init.rs
- src/commands/key.rs
allow request for new key to prompt user to confirm the password they entered
> allow request for new key to confirm entered pass

- src/commands/forget.rs
Fix "forget" command not removing provided IDs' snapshots. Its says nothing to remove when there are snapshots matching  the id
> Fix "forget" command not removing provided IDs' snapshots

- util/systemd/rustic-backup@.service
- util/systemd/rustic-backup@.timer
- util/systemd/rustic-forget@.service
- util/systemd/rustic-forget@.timer
(Related to [this discussion](https://github.com/rustic-rs/rustic/discussions/609#discussioncomment-6262498))
One thing that I think is particularly handy with crestic and config profiles is the possibility of creating systemd timers that periodically run backups and forgets. In the case of the config files of this PR, backup would run daily, forget would run monthly.
Right now the files in the PR are not really installed anywhere because `cargo build` doesn't support creating datafiles or creating Linux packages, so I guess it'd be the task of the downstream packagers to put these files in the packages. There are two locations where these files could go:
- `/usr/lib/systemd/system/` for system units (i.e. run by `root` and config files in `/etc/`)
- `/usr/lib/systemd/user` for user units …
> Systemd timers for backup and forget

- crates/rustic_core/examples/backup.rs
- crates/rustic_core/src/archiver.rs
- crates/rustic_core/src/archiver/parent.rs
- crates/rustic_core/src/backend/ignore.rs
- crates/rustic_core/src/commands.rs
- crates/rustic_core/src/commands/backup.rs
- crates/rustic_core/src/commands/cat.rs
- crates/rustic_core/src/commands/dump.rs
- crates/rustic_core/src/commands/restore.rs
- crates/rustic_core/src/lib.rs
- crates/rustic_core/src/repofile/snapshotfile.rs
- crates/rustic_core/src/repository.rs
- src/commands/backup.rs
- src/commands/diff.rs
This PR not only refactors the backup command, but also introduces several new states for `Repository`:
- `IndexedTree`: index contains only tree information
- `IndexedIds`: index additionally contains information about data IDs (e.g. needed for backup)
- IndexedFull: index contains all information
By using the state type pattern and suitable traits, methods on the `Repository` are restricted to what kind of index information is needed to process them. So, to run `backup`, you need to have either `IndexedIds` or `IndexedFull`. To run `ls`, any of the `Indexed*` states is valid. To run `prepare_restore` or `dump`, you need to be in the `IndexedFull` state.
> refactor backup command

- changelog/new.txt
- config/full.toml
- crates/rustic_core/src/backend/rest.rs
Default number of retries is set to 5.
> rest/rclone: make # of retries cusomizable and use sensible default

- changelog/new.txt
- crates/rustic_core/src/backend/ignore.rs
- crates/rustic_core/src/backend/local.rs
- crates/rustic_core/src/backend/node.rs
- crates/rustic_core/src/commands/restore.rs
- crates/rustic_core/src/error.rs
- src/commands/diff.rs
- src/commands/ls.rs
After this has been added to the restic repository format (https://github.com/restic/restic/pull/3802), this can be also handled within rustic.
Note that for windows, this PR assumes that there are no non-unicode link-targets.
closes #117
> handle non-unicode link-targets

- .cargo/config.toml
- .github/workflows/lint-markdown-toml.yaml
- .github/workflows/lint-markdown.yaml
- CONTRIBUTING.md
- Cargo.toml
- README.md
- config/README.md
- config/copy_example.toml
- config/full.toml
- config/local.toml
- config/ovh-hot-cold.toml
- config/par2.toml
- config/rustic.toml
- crates/rustic_core/Cargo.toml
- crates/rustic_core/README.md
- crates/rustic_core/src/cdc/README.md
- crates/rustic_testing/Cargo.toml
- docs/FAQ.md
- docs/comparison-restic.md
- dprint.json
- xtask/Cargo.toml
For our documentation efforts within the repository, it makes sense to introduce a common style that is easy to uphold using `dprint`. Also, because `dprint` is just a `cargo install dprint`/`scoop install dprint` away.
> ci: Lint markdown with dprint, run initial dprint fmt

- Cargo.toml
After merge, we can add that to the installation section's `From binaries` in #820
> chore: add support for `cargo-binstall`

- Cargo.toml
For #950: If one has "cargo-generate-rpm" installed, then this makes it easy to create an RPM file from the result of a release build. If one doesn't have "cargo-generate-rpm" installed, the extra Cargo.toml lines don't make a difference.
closes #950
> #950: Enable RPM file build target

- src/application.rs
- src/commands.rs
- src/config.rs
This PR logs outputs from reading config files like all other logs. It does so by collecting the messages and once the logger is started (which is after *all* config files have been processed), it performs the logging of all collected messages.
It also changes the severity of missing config files: If no config file is given in the command line, a missing `rustic.toml` is an info error. All other missing config files will produce warnings.
closes #959
> fix: log config file logs after reading config files

- src/commands/backup.rs
- src/commands/copy.rs
A user discovered that for some commands they are not being asked for a password, although they should. This implements a fix for the backup and copy command so they consistently call the same functionality that is being used for the other commands. Hence, asking for the password, if it's missing.
> fix(commands): Ask for password in backup and copy command if it is missing

- config/services/b2.toml
> fix(doc): Correct b2.toml

- Cargo.lock
- Cargo.toml
- config/full.toml
- config/services/b2.toml
- src/commands.rs
Reads the env variables `RUSTIC_REPO_OPT_*`, `RUSTIC_REPO_OPTCOLD_*`, `RUSTIC_REPO_OPTHOT_*` to set repository options. Also reads `OPENDAL_*` variables which may be used to explicitly set opendal options (as they are in snake and not kebab case).
closes #1073
> feat: Allow setting extra repository options via env variables

- src/commands.rs
If opening or creating the logfile fails, rustic now shows the filename to allow users debug the error.
closes #1105
> fix: show log filename if open/creation failed

- config/README.md
- config/full.toml
- src/commands/backup.rs
- tests/show-config-fixtures/empty.txt
-- BREAKING CHANG --
Using multiple paths for a sources in the config file caused many problems as the syntax was unclear and problems existed in edge cases.
This PR changes the definition of sources in config profile files:
- a single path path can be specified as before, i.e. using `source = "/my/path"`.
- multiple paths must now be given in an array:
```
source = ["/my/path1", "/my/path2"]
```
Note that 
```
source = "/my/path1 /my/path2"
```
is now interpreted a a single path using the dir-tree "my","path1 " (with space), "my", "path2".
closes #1122
closes #1094
> fix(config)!: multiple paths in config profile as array

- src/commands/tui/ls.rs
- src/commands/tui/restore.rs
- src/commands/tui/snapshots.rs
restore:
- propose path from snapshot as target
- handle empty target
write snapshots:
- clarify that you can enter (y/n)
> more interactive improvements

- src/commands/diff.rs
closes rustic-rs/rustic#440
The proposed code contains:
- a DiffStatistics structure used to hold count of stats
- this structure offers a few helping functions that will look at a given NodeType to increment the associated counter
- it has a Display implementation used to display the statistics in STDOUT
- this structure is used in the `diff` function
```bash
rustic --log-level debug -r test-repo --password password diff 8e57051d:config ./config
[INFO] using no config file, none of these exist: /home/nardor/.config/rustic/rustic.toml, /etc/rustic/rustic.toml, ./rustic.toml
[INFO] repository local:test-repo: password is correct.
[INFO] using cache at /home/nardor/.cache/rustic/3797e1fe324e97ac068e303e672da3d34af09cd73888bcfd09538cd72692bf7d
[00:00:00] reading index... …
```
> feat(diff): show diff statistics

- Cargo.lock
- src/commands/backup.rs
- src/commands/diff.rs
- src/commands/find.rs
- src/config.rs
**Add auto completion hints**
This helps some shells to propose better completions.
For instance on `zsh`, no completion were proposed when doing `rustic backup <...>[TAB]`
- `rustic backup <...>[TAB]`
- `rustic backup --as-path [TAB] <...>`
- `rustic backup --stdin-filename [TAB] <...>` This one is for comfort, as the compl might not help (or might), but my opinion is that it's better than nothing.
- `rustic diff <snapshot_id> <...>[TAB]`
- `rustic find --path <...>[TAB]`
- rustic --log-file <...>[TAB]`
> feat: Add autocompletion hints

- src/application.rs
rustic now returns an error code for failing command.
Note: Some command do not fail yet fail in every cases user would expect is. Most notably the `check` ckommand producing `error` messages may still return error code 0.
closes #927
> fix: return exitcode

- src/commands/tui/snapshots.rs
Adds the possibility to edit the filter used in the interactive snapshots view: 
- use 'V' to view or change the filter
- use 'Ctrl-v' to reset to the filter as given to the command
> feat(interactive): Allow to modify filters

- src/commands/tui/ls.rs
- src/commands/tui/widgets.rs
- src/commands/tui/widgets/text_input.rs
Adds the possibility to view text files up to 1MiB  in the interactive snapshot tree view. Note this is a quick-and-dirty implementation which could be improved better non-text-files and which could be optimized to read files of all sizes
> feat(interactive): Allow to view text files

- src/commands.rs
- src/commands/init.rs
Companion PR for https://github.com/rustic-rs/rustic_core/pull/265
It renames `PasswordCommandParsingFailed` to `PasswordCommandExecutionFailed`
> doc: update RepositoryErrorKind rustdoc following rustic_core change

- src/commands/forget.rs
- src/commands/webdav.rs
The `inner_run` implementation used `self`
to read its config when it should use `RUSTIC_APP.config()`.
Some might say this is counterintuitive.
fixes #1163
also now correctly respects having `prune = true` in the config profile.
> fix: webdav/forget: correctly use application config

- src/commands/ls.rs
Paths are separated by a newline, printing space only hinders parsing. Also paths are now displayed using `Path::display()`.
> fix: ls: Remove printing trailing space

- src/commands/restore.rs
reduce memory usage of the `restore` command by removing the data entries from the index before doing the actual restore.
see https://github.com/rustic-rs/rustic/issues/1067
TODO:
> perf: Reduce memory usage of restore

- Cargo.lock
- Cargo.toml
- src/commands/backup.rs
- src/commands/copy.rs
- src/commands/forget.rs
- src/commands/key.rs
- src/commands/tui/restore.rs
- src/commands/webdav.rs
- src/config.rs
- src/config/progress_options.rs
- src/filtering.rs
Due to changes in the way how merging of values were applied to configuration values in `BackendOptions` this should is considered a fix. Now values from the configuration file don't overwrite values from environment variables, any more. As it was intended and stated in the documentation.
Please make sure, your workflow is still working as intended, especially that the configuration values and environment variables are applied as you wanted it and as we documented it in the Configuration documentation.
Precedence also applies when inheriting options from other profiles using `use-profiles` or when using multiple profiles, e.g. `rustic -P one -P two`. If the same repository option is defined in `one` and `two` the value of `one` is taken. Before the fix, the value of `two` was taken. But …
> fix(deps): update rustic_core and other dependencies and fix merge precedence

- .github/workflows/ci.yml
- .github/workflows/cross-ci.yml
Currently, we are not testing with all features, as `self-update` is missing. This PR adds it back.
> ci: add missing feature self-update to tests and checks

- Cargo.lock
- Cargo.toml
This contains an immediate fix for a newly introduced bug in `rustic_core v0.5.2` that involved how the `TreeStreamerOnce` handled errors when a channel was full.
Fixes v0.9.2 breaks prune operations #1313
> fix(deps): update rustic_core to version 0.5.3

- src/commands.rs
Fix clippy lints which came from updated Rust version. We now use `Box` for all commands.
> fix: clippy lints for new Rust version

- Cargo.lock
- Cargo.toml
- src/commands/tui/widgets/select_table.rs
chore(deps): update dependencies: tokio, ratatui, and tui-textarea
fix(clippy): use of deprecated method `ratatui::widgets::Table::<'a>::highlight_style`: use `Table::row_highlight_style` instead
> chore(deps): update tokio, ratatui, and tui-textarea

- Cargo.lock
- Cargo.toml
- config/full.toml
- deny.toml
- src/commands.rs
- src/commands/mount.rs
- src/commands/mount/fusefs.rs
- src/commands/webdav.rs
- src/config.rs
This PR adds the `mount` command to rustic to access snapshot contents as a read-only filesystem when the feature-flag `mount` is chosen. 
As for the `webdav` command, there are following options:
- Access to a concrete snapshot/path, e.g. `rustic mount /mnt 37a63e5b:/my/path`.
- Access to all snapshots (maybe restricted by filters) by using templates to define a virtual directory structure where snapshots are located. Example: `rustic mount /mnt --path-template "[{hostname}]/[{label}]/{time}" --time-template "%Y-%m-%d_%H-%M-%S"` (these are also defined as default). Note that for all dirs containing only snapshots, also a `latest` entry is generated. `latest` and identical subsequent snapshots are symlinks when using `mount`.
This PR uses fuse_mt which is not optimal as it introduces some …
> feat(commands): Add `mount` command

- .github/workflows/cross-ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release-cd.yml
- .github/workflows/release-image.yml
- Dockerfile
- build-dependencies.just
This PR create a new building target `aarch64-unknonw-linux-musl`, as `aarch64-unknonw-linux-gnu` is not competible with the docker base image `scratch`. 
Follows the current step, the arm64 docker image will be built after Github release.
> build(docker): support arm64 docker image

- .cargo/audit.toml
- .github/workflows/cross-ci.yml
- .github/workflows/nightly.yml
- .github/workflows/prebuilt-pr.yml
- .github/workflows/release-cd.yml
- Cargo.lock
- Cargo.toml
- deny.toml
- src/config.rs
> chore(deps): update dependencies and migrate to conflate 0.3, rustic_core/backend/testing on main

- src/commands/webdav.rs
- src/commands/webdav/webdavfs.rs
Solves the webdav problem reported in #1181
> fix(filesystem): Use channels to communicate within webdav filesystem

- src/commands/webdav/webdavfs.rs
(after reverting #1361)
solves the webdav problem reported in #1181
> fix(commands): Use spawn_blocking in webdav when calling rustic_core

- config/README.md
- config/full.toml
Adds documentation for the minutely timeline (https://github.com/rustic-rs/rustic_core/pull/374) in `./config/full.toml` and `./config/README.md`
> docs: Add documentation for `minutely` keep option

- Cargo.lock
- Cargo.toml
- config/README.md
- config/full.toml
- src/error.rs
- src/filtering.rs
- src/snapshots/rustic_rs__config__tests__default_config_passes.snap
- src/snapshots/rustic_rs__config__tests__global_env_roundtrip_passes-3.snap
Adds filtering using `jq` syntax. You can do something like `--filter-jq '.summary.files_new > 51'` - works similar to what you'd expect from `jq`.
Also puts the `rhai` and `jq` filtering into features which are enabled by default.
> feat: Add --filter-jq option

- Cargo.lock
- Cargo.toml
- src/commands.rs
If you have a long-running process, like `webdav` or `backup` or others, pressing CTRL+C usually results in a non-zero exit code:
`process didn't exit successfully: P:\CARGO\.cargo-target-win\debug\rustic.exe -P <PROFILE> webdav (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)`
This shouldn't be the case, as it was user initiated and we can shut down gracefully.
This PR adds this functionality, so CTRL+C shuts down `rustic` gracefully and exits with a 0 exit-code.
> feat: shut down gracefully with ctrl+c

- src/commands/backup.rs
The `backup` `run-before` hook is now run before checking the source dirs allowing to mount backup sources there.
closes #1373
> fix: run backup hooks before checking source dir

- src/bin/rustic.rs
In a complex program the cause of SIGPIPE is unclear, it may come from socket writes, or even socket reads under some conditions, as well as on writes to pipes. As rustic depends on third party libraries to perform IO and handle sockets, it has little power to control the socket and operation flags for all IO to ensure that SIGPIPE has a clear meaning.
Per a comment on #1326 the original intent was to catch a SIGPIPE from a use case such as `command | rustic backup -` however this situation will not create a SIGPIPE anyway, and if it did it would likely result in incomplete data due to command exiting immediately after writing into the pipe buffer, rather than after all pipe buffer data has been read. The behavior of pipes in this case is to EOF after all writers have completed and all …
> fix(commands): remove SIGPIPE default handler

- src/commands.rs
#1392 was unfortunately ambiguous. IMO the better option to solve #1391 is to use OPENDALHOT_* and OPENDALCOLD_* env variables.
> fix: rename OPENDAL_HOT_*/COLD_* to OPENDALHOT_*/COLD_*

- src/config.rs
> fix: Don't allow wrong commands in front of valid ones

- src/commands.rs
- src/commands/backup.rs
- src/commands/forget.rs
- src/commands/prune.rs
- tests/backup_restore.rs
This PR extends the logging. For `backup`, `forget`, `prune` the stdout output is now printed via an INFO log which allows to see this information also in the log file.
Moreover, when using a log file, rustic now also logs the version and the used command.
closes #1454
closes #1080
> feat(commands)!: Extend logging

- src/commands/snapshots.rs
If no grouping is given, the json output now displays all snapshots without artificial grouping.
Also, in this case, the group is not displayed in non-json output.
closes #1362
> feat(commands)!: Fine-tune output for snapshots command when no grouping is given

- Cargo.lock
- src/commands/key.rs
> feat(commands): Add missing key subcommands

- src/commands/ls.rs
- src/commands/tui/ls.rs
In the interactive `ls` view, the key `s` now recursively computes the summary (files, size, dirs) instead of showing zero size and files for dirs.
> feat(interactive): ls: Add options to compute cumulative statistics

- config/README.md
This PR fixes the misleading description of the `exclude-if-present` config option. (It now is more similar to the description provided at https://rustic.cli.rs/docs/commands/backup/excluding_files.html)
> docs(config): Correct the `exclude-if-present` option descritption

- Cargo.toml
- config/README.md
- config/full.toml
- src/error.rs
- src/snapshots/rustic_rs__config__tests__default_config_passes.snap
- src/snapshots/rustic_rs__config__tests__global_env_roundtrip_passes-3.snap
By default, rhai support for filtering snapshots (`--filter-fn`) is now not compiled in, but the compile feature still exists.
In future we might remove it completely as we now have `filter-jq` with similar possibilities.
> change!: Remove --filter-fn from default

- config/README.md
- src/commands/backup.rs
- src/commands/find.rs
- src/commands/forget.rs
- src/commands/snapshots.rs
- src/config.rs
- src/snapshots/rustic_rs__config__tests__default_config_passes.snap
- src/snapshots/rustic_rs__config__tests__global_env_roundtrip_passes-3.snap
`group-by` can now be given as a global option.
This also allows to set it in the config profiles or use the env variable `RUSTIC_GROUP_BY`.
> feat(commands): make group_by a global option

- src/commands/backup.rs
> fix: sanitize paths after run-before hook

- src/metrics/prometheus.rs
Previously, this was using the global registry (via register_gauge!), which doesn't support re-registering metrics in this way, so only the first call to `PrometheusExporter::push_metrics` would succeed, while any later calls would return a (nested) `prometheus::Error::AlreadyReg`.
This resulted in only the metrics for the first snapshot being pushed, while the metrics for subsequent snapshots errored with a somewhat vague error (the interior messages are not shown):
```
[WARN] error pushing metrics: pushing prometheus metrics
```
This PR more closely matches the behavior of the OpenTelemetry backend, which similarly only pushes the immediately-passed (as an argument) metrics, rather than including other metrics previously registered globally, as was the behavior with …
> fix(metrics): use short-lived local registry
