rustic-rs/rustic

- src/backend/ignore.rs
This at least makes it compile, and pass what tests there are on my macbook.
> Use `unix` metadata extensions, rather than linux-specific ones

- src/archiver/archiver_impl.rs
- src/backend/ignore.rs
- src/main.rs
- src/repo/snapshotfile.rs
This PR makes checks by `cargo clippy` a bit stricter. Hoping this will further  improve the quality of rustic..
> Add more lints

- src/commands/prune.rs
In prune there is the logic that packs-marked-for-deletion are decided first.
This ensures that the deletion of a pack which is marked for deletion is completed if each used blob in the pack is also contained in another pack which is not marked for deletion.
However, the order of the loop wasn't correct: So far only the marked packs WITHIN an index file were processed first. We however want to have all marked packs for all index files to be processed first.
As a result, depending on the order if index files, some marked packs were uneccessarily recovered and other were maybe uneccessarily repacked.
This is fixed by this PR.
Note that the previous behavior did not lose data or left the repo in an inconsistent state, but it made `prune` do some uneccessary work or not delete things as fast …
> prune: do not recover uneccessarily

- src/backend/rest.rs
> REST backend: ensure that url ends with '/' and fix config path

- src/backend/node.rs
> fix possible node types

- src/backend/local.rs
> local BE: only use valid files

- src/blob/tree.rs
> Allow null nodes in JSON tree

- src/blob/packer.rs
don't flush temporary file and go earlier to backgroud for saving
> Speed up packer

- src/commands/prune.rs
Add the option `--instant-delete` to `prune`. With this option, `rustic prune` uses no two-phase pruning but removes unneeded pack files immediately.
This is identically to the behavior of restic except that no locks are created. 
USE THIS OPTION WITH CARE!
The option is interesting for exclusive pruning, especially in combination with #7.
> prune: Add option --instant-delete

- src/commands/prune.rs
Adds the option `--repack-uncompressed` to `prune`.
Also changes the default prune repacking behavior to re-compressing and re-encrypting the blobs.
This also checks verifies each  blob content when repacking.
The old behavior (only copy the contents without any change or check) can be still achieved by using the new option `--fast-repack`.
Especially on older hardware which does not support hardware-accelerated de/encryption or fast (de)comprepression, the option `--fast-repack` can increase repacking speed.
> prune: add options --repack-uncompressed and --fast-repack

- src/backend/rclone.rs
When using the rclone backend, the url which was internally used by the REST backend ended with a newline. 
This had the very nasty effect that reqwest silently turned all POST/DELETE requests into GET requests and therefore no writes to the repository were made.
This is now changed.
Additionally the output of rclone is printed if the verbosity level is high enough.
> rclone: fix url and allow debug output

- src/commands/snapshots.rs
Adds the possibility to use `snapshots latest` which only prints the latest snapshot.
This is handy in combination with `--group-by` to show the latest snapshot for each group.
> snapshots: allow argument "latest"

- src/backend/local.rs
- src/commands/restore.rs
This PR improves the `restore` command and especially fixes some situations where rustic did abort or work wrong.
Closes #66
> restore: improvements

- src/commands/helpers.rs
- src/commands/prune.rs
- src/commands/restore.rs
Improves the progress bars for `prune` and `restore`
> Better progress bars

- src/backend/local.rs
- src/commands/restore.rs
With this PR, `restore` checks the contents of possibly existing files-to-restore (if the size also matches).
If contents match to blobs which would be restore, they are used to:
- omit the content restore for these blobs (as they are already correct)
- use that data to restore other files which need the same blobs
This can extremely speed-up the restore and minimizes read-access to the repository.
Moreover, now aborted restores can be efficiently resumed. 
It also allows to verify if a backup matches existing data by simply running `restore -n` and checking that `restore` reports all file contents are fine.
Note that this PR may slow down the restore in some edge cases compared to the current behavior:
- if reading from the restore destination is very slow
- if many/big  files are read …
> restore: use existing fileparts

- src/commands/restore.rs
> restore: Add warm-up options

- FAQ.md
> Add more info about two-phase pruning

- src/commands/helpers.rs
- src/commands/prune.rs
- src/commands/restore.rs
Adds warm-up options to `prune` (for the packs-to-repack) and also adds the option `--warm-up-wait` which allows to wait a given time between warm-up and doing the actual operation.
closes #67
> More warm-up options

- Cargo.toml
- src/commands/mod.rs
> Add support for environmental variables

- src/backend/ignore.rs
- src/commands/backup.rs
- src/commands/cat.rs
- src/commands/check.rs
- src/commands/config.rs
- src/commands/diff.rs
- src/commands/forget.rs
- src/commands/init.rs
- src/commands/key.rs
- src/commands/list.rs
- src/commands/ls.rs
- src/commands/mod.rs
- src/commands/prune.rs
- src/commands/restore.rs
- src/commands/snapshots.rs
- src/commands/tag.rs
- src/repo/snapshotfile.rs
This PR optimizes the help texts and adds grouping.
closes #106 
closes #111
> Improve help texts

- src/archiver/parent.rs
With this PR, the search for a parent node uses the fact that trees are sorted. 
closes #152
> backup: Speed up searching for parent node

- src/backend/ignore.rs
also changed sorting/grouping of exclude options in help text
> backup: Add option --exclude-larger-than

- src/commands/forget.rs
Applying keep policies to given snapshot IDs in the forget command is actually irritating.
Even more after #169 is merged and keep policies can be given in the config file (and not "removed" by command line options)
> forget: Don't apply keep policy for given ids

- src/commands/prune.rs
> prune: fix max-repack option

- src/chunker.rs
closes #198 
Also increases the buffer used by the chunker to 64kiB. (This boosts performance a bit)
> Fix chunker and increase buffer.

- src/backend/node.rs
> escape filename like restic

- src/commands/forget.rs
- src/commands/snapshots.rs
- src/repo/snapshotfile.rs
This PR implements `Display for SnapshotGroup`
> Nicer display for SnapshotGroups

- src/commands/backup.rs
> backup: Add --host option

- src/commands/helpers.rs
- src/commands/init.rs
- src/commands/key.rs
- src/commands/mod.rs
> init: use password if given

- src/backend/rest.rs
> REST backend: handle errors correctly

- src/commands/restore.rs
> restore: Print what will be done in debug log

- src/backend/decrypt.rs
- src/backend/dry_run.rs
- src/commands/check.rs
- src/commands/helpers.rs
- src/commands/mod.rs
- src/commands/prune.rs
- src/commands/repair.rs
- src/commands/restore.rs
- src/repo/packfile.rs
> Add repair index command

- .github/workflows/release.yaml
> Fix race condition when uploading beta builds

- src/commands/helpers.rs
> Progress: Add support for env variable RUSTIC_PROGRESS_INTERVAL

- src/archiver/archiver_impl.rs
- src/blob/packer.rs
- src/commands/prune.rs
> Parallelize packer

- src/commands/cat.rs
- src/commands/diff.rs
- src/commands/ls.rs
- src/commands/mod.rs
- src/commands/restore.rs
closes #247 
Note that `latest` for diff is so far only supported when diffing with a local dir.
> Better support for `latest`

- Cargo.lock
- Cargo.toml
- src/main.rs
> fix broken pipe panic

- src/blob/packer.rs
> fix possible deadlock in archiver

- Cargo.lock
- Cargo.toml
- src/commands/helpers.rs
> fix 0B/s in ProgressBar

- src/backend/rclone.rs
> rclone backend: Be more relaxed about version check

- src/blob/tree.rs
- src/commands/cat.rs
- src/commands/diff.rs
- src/commands/ls.rs
- src/commands/restore.rs
> Allow file with SNAP:PATH syntax

- src/backend/rclone.rs
> Fix rclone backend for rclone 1.61

- src/backend/decrypt.rs
- src/backend/mod.rs
- src/backend/rest.rs
- src/commands/copy.rs
- src/commands/forget.rs
- src/commands/prune.rs
- src/commands/repair.rs
- src/commands/tag.rs
Some changes which came out of a code review...
> Code review

- src/commands/diff.rs
This PR adds the options
- `--metadata` which is disabled by default and shows if file contents are identical, but metadata changed. The output for only metadata changes is now changed to `U`, similar to `restic diff`.
- `--no-content` to disable the check for identical content. This is disabled by default. If it is disabled, then file contents are read when comparing a snapshot with a local dir. This option has been mainly added to get the current behavior when diffing with local dirs, i.e. only compare metadata. This is very fast as files don't need to be read. Note that this option is pretty useless when comparing two snapshots as the check for identical contents is almost free here.
Moreover, type changes are now indicated by `T`, as in `restic diff`.
Note: The previous behavior of …
> diff: Add options --metadata and --no-content

- src/commands/check.rs
- src/commands/prune.rs
> remove unneeded packs in cache in check instead of prune

- Cargo.lock
- Cargo.toml
- src/repository/mod.rs
see #376 
This PR corrects the tokenization of the command string and adds debug output for the result.
> fix password-command

- src/commands/prune.rs
The prune problem #392 is corrected in this PR.
> prune: fix check for needed packs

- src/commands/restore.rs
> restore: Don't abort on delete errors

- src/backend/local.rs
- src/commands/diff.rs
- src/commands/restore.rs
> diff/restore: Treat single file destination properly

- src/repository/mod.rs
> Read password from file not containing trailing newline 

- src/commands/backup.rs
> backup: add option --json

- src/commands/backup.rs
fixes a regression introduced by #462
> re-allow to use [[backup.sources]] in config file

- src/commands/check.rs
- src/index/binarysorted.rs
> check --read-data: Show progress in bytes

- src/commands/backup.rs
> backup: fix problem with multiple sources in config

- changelog/new.txt
- src/commands/config.rs
> config: Save config file uncompressed

- src/commands/merge_cmd.rs
> merge: set timestamp

- src/commands/restore.rs
> restore: Add --no-ownership option

- src/archiver/tree.rs
- src/blob/tree.rs
This PR treats the path prefixes available under windows, like `C:\` or `\\server\path\`
> windows: treat path prefixes

- changelog/new.txt
- src/commands/restore.rs
> restore: Fix restoring of empty files

- changelog/new.txt
- src/backend/rest.rs
> REST backend: Set User-Agent

- changelog/new.txt
- src/backend/ignore.rs
- src/commands/completions.rs
- src/commands/repair.rs
- src/commands/restore.rs
> Fix shell completions

- src/backend/cache.rs
- src/backend/choose.rs
- src/backend/decrypt.rs
- src/backend/dry_run.rs
- src/backend/hotcold.rs
- src/backend/local.rs
- src/backend/mod.rs
- src/backend/rclone.rs
- src/backend/rest.rs
- src/repository/mod.rs
> repository: Use location in log // don't show password

- examples/local.toml
- examples/ovh-hot-cold.toml
> correct one-file-system in examples

- src/backend/local.rs
See #552.
This PR hopefully helps with the error tracking or even fixes it.
> restore/xattr: Improve implementation and errors

- changelog/new.txt
- src/blob/tree.rs
- src/commands/ls.rs
> ls: Add option --recursive

- changelog/new.txt
- src/backend/local.rs
- src/blob/tree.rs
- src/commands/ls.rs
- src/commands/restore.rs
> restore/ls: Add glob options to include/exclude patterns

- changelog/new.txt
- src/backend/stdin.rs
- src/commands/backup.rs
> backup: Fix --stdin-filename

- changelog/new.txt
- src/backend/local.rs
- src/commands/restore.rs
> restore: Don't follow symlinks when setting time/modes

- changelog/new.txt
- src/archiver/mod.rs
- src/archiver/tree_archiver.rs
- src/commands/backup.rs
> backup: only show changed dirs if there are changes

- Cargo.lock
- Cargo.toml
- changelog/new.txt
- src/backend/ignore.rs
- src/blob/tree.rs
- src/commands/backup.rs
- src/commands/cat.rs
- src/commands/check.rs
- src/commands/completions.rs
- src/commands/config.rs
- src/commands/copy.rs
- src/commands/diff.rs
- src/commands/dump.rs
- src/commands/forget.rs
- src/commands/helpers.rs
- src/commands/init.rs
- src/commands/key.rs
- src/commands/list.rs
- src/commands/ls.rs
- src/commands/merge_cmd.rs
- src/commands/mod.rs
- src/commands/prune.rs
- src/commands/repair.rs
- src/commands/restore.rs
- src/commands/snapshots.rs
- src/commands/tag.rs
- src/repofile/snapshotfile.rs
- src/repository/mod.rs
> update clap to v4

- changelog/new.txt
- src/commands/backup.rs
- src/commands/copy.rs
- src/commands/forget.rs
- src/commands/mod.rs
- src/commands/prune.rs
- src/commands/repair.rs
- src/commands/restore.rs
- src/commands/self_update.rs
- src/commands/tag.rs
> Make --dry-run a global option

- Cargo.lock
- Cargo.toml
- changelog/new.txt
- src/archiver/file_archiver.rs
- src/archiver/mod.rs
- src/archiver/tree_archiver.rs
- src/blob/packer.rs
- src/commands/copy.rs
- src/commands/merge_cmd.rs
- src/commands/repair.rs
- src/crypto/hasher.rs
This is a quick shot and definitively not the best we can do.
However gives an ides how the `backup` command could be parallelized.
closes #554
> Parallelize backup of files

- Cargo.lock
- Cargo.toml
- src/archiver/file_archiver.rs
- src/archiver/parent.rs
- src/archiver/tree_archiver.rs
- src/backend/local.rs
- src/backend/node.rs
- src/blob/packer.rs
- src/blob/tree.rs
- src/commands/check.rs
- src/commands/copy.rs
- src/commands/diff.rs
- src/commands/prune.rs
- src/commands/repair.rs
- src/commands/repoinfo.rs
- src/commands/restore.rs
- src/index/binarysorted.rs
- src/index/mod.rs
- src/repofile/indexfile.rs
This simplifies the code and also removes some dependencies
> Remove getters and setters from code

- changelog/new.txt
- src/backend/ignore.rs
- src/commands/backup.rs
- src/commands/diff.rs
> diff: remove unwanted options

- doc/comparison-restic.md
And also improve sentence structure.
> comparison-restic: fix typo

- changelog/new.txt
- src/commands/copy.rs
- src/commands/init.rs
- src/commands/key.rs
> copy: Add --init option

- Cargo.lock
- crates/rustic_core/Cargo.toml
- crates/rustic_core/src/archiver.rs
- crates/rustic_core/src/archiver/file_archiver.rs
- crates/rustic_core/src/backend/cache.rs
- crates/rustic_core/src/backend/decrypt.rs
- crates/rustic_core/src/blob/tree.rs
- crates/rustic_core/src/index.rs
- crates/rustic_core/src/lib.rs
- crates/rustic_core/src/progress.rs
- crates/rustic_core/src/repofile/snapshotfile.rs
- src/commands/backup.rs
- src/commands/cat.rs
- src/commands/check.rs
- src/commands/copy.rs
- src/commands/diff.rs
- src/commands/dump.rs
- src/commands/forget.rs
- src/commands/list.rs
- src/commands/ls.rs
- src/commands/merge.rs
- src/commands/prune.rs
- src/commands/repair.rs
- src/commands/repoinfo.rs
- src/commands/restore.rs
- src/commands/snapshots.rs
- src/commands/tag.rs
- src/config/progress_options.rs
- src/helpers.rs
- remove printing of error messages from `rustic_core`
- remove dependency from `indicatif` from `rustic_core`
> More refactoring

- Cargo.lock
- Cargo.toml
> change tls to tls-native-roots

- crates/rustic_core/src/backend/rest.rs
> rest backend: Allow null value in json

- .github/workflows/release.yaml
> Add binary for raspberry pi

- Cargo.toml
- crates/rustic_core/Cargo.toml
add categories and msrv to rustic_core/rustic manifest, include examples and config folder in packaging, update workspace dependencies
> refactor: Add metadata to crate manifests

- src/commands/init.rs
> init: Handle option --dry-run

- src/application.rs
referenced here: https://github.com/rustic-rs/rustic/discussions/907#discussioncomment-7264998
> Fix term log level limiter when `log-file` option set

- src/config/progress_options.rs
needed to solve #960 and #689.
> support progress bars without length

- src/commands/ls.rs
see https://github.com/rustic-rs/rustic/discussions/503#discussioncomment-8254371
> feat: Add option --numeric-uid-gid to ls

- src/config/progress_options.rs
> fix: Fix possible overflow in progress bar ETA

- src/commands/ls.rs
- src/commands/tui.rs
- src/commands/tui/ls.rs
- src/commands/tui/snapshots.rs
- src/commands/tui/widgets.rs
Is currently only inlcuded in `rustic snapshots -i`.
> feat: Add interactive ls mode

- Cargo.lock
- src/commands/snapshots.rs
- src/commands/tui.rs
- src/commands/tui/snapshots.rs
- src/commands/tui/tree.rs
The interactive snapshots view now also groups snapshots.
> Interactive snapshots groups

- src/commands.rs
Times in logfiles are now printed in RFC3339 format
closes #1076
> feat(logging): use RFC3339 time format in logfile

- src/commands/tui.rs
- src/commands/tui/ls.rs
- src/commands/tui/restore.rs
- src/commands/tui/snapshots.rs
- src/commands/tui/widgets.rs
- src/commands/tui/widgets/text_input.rs
> feat(interactive): Add possibility to change snapshot description

- src/commands/tui.rs
- src/commands/tui/snapshots.rs
If a panic happens, the interactive screen is now reset so the terminal can show the panic output.
Moreover, "to-delete" was renamed to "to-forget" and the key bindings were changed to f / Ctrl-f.
> interactive improvements: reset screen on panic; key bindings

- src/commands/forget.rs
> fix: Respect delete-protection when running forget with ids

- Cargo.lock
- Cargo.toml
- Dockerfile
- README.md
- src/commands/find.rs
- src/commands/snapshots.rs
- src/commands/tui.rs
- src/commands/tui/progress.rs
- src/commands/tui/snapshots.rs
- src/commands/tui/widgets/text_input.rs
> chore(deps): Update dependencies

- src/commands/snapshots.rs
> fix(build): allow to compile without tui feature

- .github/workflows/ci.yml
> fix(build): Use cargo --locked in CI pipeline

- src/commands/ls.rs
> fix: make ls and find show the year of mtime date

- src/commands/tui/snapshots.rs
> fix(interactive): Allow snapshots to be modified and marked to forget

- Cargo.lock
- src/commands/list.rs
This allows better analysis of reported bugs related to the index.
> feat(commands): Add list indexpacks and list indexcontent commands

- config/README.md
> fix(docs): update configuration documentation to align with recent changes

- src/commands/tui/snapshots.rs
This increases speed of refreshing a lot.
> perf(interactive): use update methods for refreshing snapshots

- Cargo.lock
- Cargo.toml
- rustic_core to 0.5.1
- rustic_backend to 0.4.1
- open to 5.3.0
> chore(deps): upgrade dependencies

- Cargo.lock
- Cargo.toml
Fixes #1291
Related: https://github.com/jaemk/self_update/issues/136
> fix(deps): downgrade self-update to fix problems finding right target

- Cargo.lock
- Cargo.toml
Update rustic_core and rustic_backend to incorporate fixes. See their changelogs for more information.
> chore(deps): update rustic_core and rustic_backend

- Cargo.lock
- Cargo.toml
- src/commands.rs
- src/commands/dump.rs
The `dump` command will now produce a tar when called with a directory.
> feat(commands): Add tar output to dump command

- src/commands.rs
> feat: Allow to use OPENDAL_HOT_* and OPENDAL_COLD_* env variables

- src/commands/diff.rs
> feat(diff): Use local PATH1 as PATH2 if no new snapshot/path is given

- .github/workflows/nightly.yml
- .github/workflows/prebuilt-pr.yml
- .github/workflows/release-cd.yml
> re-enable architures with aws-lc-sys problems
